system:
  port: 8888 # 默认值 8888
  router-prefix: run

pgsql:
  path: "localhost"
  port: "5432"
  username: "kurous"
  password: "D4Dh3WnH4OaPpCj#"
  db-name: "test"
  config: "" # 连接参数
  max-idle: 10 # 空闲中的最大连接数
  max-open: 100 # 打开到数据库的最大连接数
  log-mode: "" # 是否开启Gorm全局日志，默认为info，可不填
  log-zap: true  # 是否通过zap写入日志文件

zap:
  level: debug
  prefix: "[run]"
  format: console
  director: logs
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1
